### ISSUE TITLE
[feat] Notes on VPNs

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#222]
Most popular VPN client apps can interfere with LAN access by default, but also have options to allow.

Known good:

Mullvad - Settings -> VPN Settings -> Local network sharing (toggle to 'on')
ProtonVPN

**Comment by BitcoinMechanic** [comment]
I had a ticket yesterday with someone who's LAN wasn't working due to Nord:

`Just one more bit of info in case anyone else runs into problems. Nord VPN has a password manager (that I don't use) that installs at the same time as the VPN. 

I had been shutting off the VPN while I was trying to get Embassy installed, thinking it was then inactive, but eventually noticed a little icon in my taskbar that indicated a Nord component being active. Even after I completely uninstalled the VPN, this password manager remained installed and active on my computer. Once I unistalled that too, then all was good to go.`

**Comment by kn0wmad** [comment]
Maybe just FAQ, or maybe it's own sub-section somewhere?

**Comment by kn0wmad** [comment]
> I had a ticket yesterday with someone who's LAN wasn't working due to Nord:
> 
> ```
> Just one more bit of info in case anyone else runs into problems. Nord VPN has a password manager (that I don't use) that installs at the same time as the VPN. 
> 
> I had been shutting off the VPN while I was trying to get Embassy installed, thinking it was then inactive, but eventually noticed a little icon in my taskbar that indicated a Nord component being active. Even after I completely uninstalled the VPN, this password manager remained installed and active on my computer. Once I unistalled that too, then all was good to go.
> ```

Nord been on a massive downhill slide for quite some time, good to know it now includes malware lol...

**Comment by BitcoinMechanic** [comment]
I think anything to do with VPNs would logically be included in the `Connecting -> LAN` section: https://docs.start9.com/latest/user-manual/connecting/connecting-lan/index

**Comment by kn0wmad** [comment]
> I think anything to do with VPNs would logically be included in the `Connecting -> LAN` section: https://docs.start9.com/latest/user-manual/connecting/connecting-lan/index

Agreed

**Comment by kn0wmad** [comment]
Closed by #273
