### ISSUE TITLE
Issue in page Configuring Firefox for Tor on Android

### ISSUE THREAD

**Issue by Fu-Om** [Start9Labs/documentation#300]
I would like to report an issue in page https://docs.start9.com/master/user-manual/connecting/connecting-tor/tor-firefox/torff-android

### Problem
Need to change `network.dns.blockDotOnion` to `false` when configuring Firefox for Tor on Android. 

###  Suggest a fix
Please consider adding the above configuration on user-manual.

**Comment by kn0wmad** [comment]
> I would like to report an issue in page https://docs.start9.com/master/user-manual/connecting/connecting-tor/tor-firefox/torff-android
> ### Problem
> 
> Need to change `network.dns.blockDotOnion` to `false` when configuring Firefox for Tor on Android.
> ### Suggest a fix
> 
> Please consider adding the above configuration on user-manual.

Can you please give your flavor and version number of Android?  This was not necessary in our testing

**Comment by Fu-Om** [comment]
The version of android is 11.
Browser is Firefox Nightly 111.0a1.
Please let me know if you need any other information.

**Comment by BitcoinMechanic** [comment]
Thanks. This is significantly older than current Android OS - I'll try and get a note added for Android v11 though it's going to be hard to confirm it's the version because I don't have anything running v11. Will leave the issue open for now.

**Comment by kn0wmad** [comment]
It would be good to know that our guides work as far back as v10, which is currently the oldest still supported by Google, but we would have to depend on the community to provide testing reports.  We also definitely want to recommend version 13 and up, since those are known to support .local addresses, and will be a superior experience.  Even this is a bit tough though, since some flavors will support .locals on older versions....

**Comment by Fu-Om** [comment]
Thanks for considering. It is good to know that it might be an android version problem.

**Comment by kn0wmad** [comment]
Closing this for now.  Can re-open if found to be more commonly problematic
