### ISSUE TITLE
[bug]: Ubuntu Firefox connot communicate with the proxy provided by proxy.pac

### ISSUE THREAD

**Issue by gStart9** [Start9Labs/documentation#490]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

Ubuntu 22.04

### Browser

Firefox

### Browser Version

116

### Current Behavior

Ubuntu's SNAP'd Firefox can be configured to use proxy.pac, but will not be able to connect to the proxy specified by the proxy.pac file.

### Expected Behavior

Firefox should be able to connect to the local tor daemon's socks5 proxy

### Steps to Reproduce

Configure proxy.pac as specified here:
https://docs.start9.com/latest/guides/device-guides/dg-linux/ff-linux

See that you cannot connect to any .onion addresses.

**Comment by 13Homer13** [comment]
It appears that the problem lies with the /etc directory, which is not allowing Firefox (ff) to access certain files. After I moved the proxy.pac file to the home directory and directed Firefox to the file's location, it started functioning correctly. Furthermore, the image is misleading since it displays the option "use system proxy" instead of "Auto proxy." In my opinion, the easiest solution would involve running the following command:

sudo wget -P ~/ https://start9.com/assets/proxy.pac

Then, you can configure Firefox to point to this file and update the image accordingly. What are your thoughts on this approach?

**Comment by gStart9** [comment]
Fixed by #494

Which will hit docs.start9.com when v0345 comes out.
